"""
Web search service.

This module provides internet search
capabilities using Tavily Search.

Search configuration is intentionally
generic so the service can support
different registered tools and domains
without embedding domain-specific logic.
"""

import os

from tavily import TavilyClient

from config.settings import TAVILY_MAX_RESULTS
from models.web_result import WebResult

# --------------------------------------------------
# Client initialization
# --------------------------------------------------


tavily_api_key = os.getenv(
    "TAVILY_API_KEY",
)

if not tavily_api_key:
    raise ValueError(
        "TAVILY_API_KEY not found in environment variables.",
    )


client = TavilyClient(
    api_key=tavily_api_key,
)


# --------------------------------------------------
# Web search
# --------------------------------------------------


def search_web(
    question: str,
) -> list[WebResult]:
    """
    Retrieve relevant web search results.

    Tavily is configured for deeper retrieval so
    broad research questions are more likely to
    return authoritative and directly relevant
    sources.

    Query construction is intentionally handled
    outside this service. This function executes
    the query it receives without adding
    domain-specific assumptions.

    Args:
        question:
            Search query generated by the agent.

    Returns:
        Normalized web search results.
    """

    query = question.strip()

    if not query:
        return []

    response = client.search(
        query=query,
        max_results=TAVILY_MAX_RESULTS,
        search_depth="advanced",
        topic="general",
    )

    results = response.get(
        "results",
        [],
    )

    return [
        WebResult(
            title=result.get(
                "title",
                "",
            ),
            url=result.get(
                "url",
                "",
            ),
            content=result.get(
                "content",
                "",
            ),
            score=result.get(
                "score",
                0.0,
            ),
        )
        for result in results
        if result.get(
            "content",
        )
    ]
