"""
Tool call model.

Represents a request made by the
AI agent to invoke a tool.
"""

from dataclasses import dataclass
from typing import Any

from models.tool import Tool


@dataclass(slots=True, frozen=True)
class ToolCall:
    """
    Represents a function call requested
    by the AI agent.

    Attributes:
        tool:
            Tool to execute.

        arguments:
            Arguments generated by the
            planning component.
    """

    tool: Tool

    arguments: dict[str, Any]

    @property
    def query(self) -> str:
        """
        Return the primary query argument.

        This compatibility property allows
        existing query-based tools to continue
        using the current interface.
        """

        value = self.arguments.get(
            "query",
            "",
        )

        if value is None:
            return ""

        return str(value)
